/**
 * ⚡️ Next-Gen AI SEO Content Optimizer Utilities
 * Handles: Generative Engine Optimization (GEO) and Answer Engine Optimization (AEO)
 */

// ==========================================
// 1. AEO: Answer Engine Optimization Tools
// ==========================================

/**
 * Validates if the content contains a dense "AI Summary" bulleted list early in the text.
 * @param {string} content 
 * @returns {boolean} True if an AI summary exists near the start
 */
export const checkAiSummaryStructure = (content) => {
  if (!content) return false;
  // Look for a block of bullet points within the first 500 characters
  const earlyText = content.substring(0, 500);
  const bulletMatches = earlyText.match(/(?:^|\n)\s*[-*•]\s+.+/g);
  // We consider an AI Summary valid if there are at least 3 dense bullet points early on
  return bulletMatches && bulletMatches.length >= 3;
};

/**
 * Parses and strictly validates JSON-LD Schema.
 * @param {string} schemaString Raw JSON-LD string
 * @returns {object} { isValid: boolean, foundTypes: array, deprecated: array, msg: string }
 */
export const validateLdJsonSchema = (schemaString) => {
  try {
    const schemas = JSON.parse(schemaString);
    const schemaArray = Array.isArray(schemas) ? schemas : [schemas];
    
    const validTypes = ['Article', 'NewsArticle', 'FAQPage', 'Product', 'Organization'];
    const deprecatedTypes = ['HowTo', 'QAPage']; // HowTo is visually deprecated in many SERP layouts by Google
    
    let foundTypes = [];
    let deprecated = [];

    schemaArray.forEach(schema => {
      const type = schema['@type'];
      if (type) {
        foundTypes.push(type);
        if (deprecatedTypes.includes(type)) {
          deprecated.push(type);
        }
      }
    });

    const isOptimized = foundTypes.some(t => validTypes.includes(t)) && deprecated.length === 0;

    return {
      isValid: isOptimized,
      foundTypes,
      deprecated,
      msg: isOptimized ? 'Schema is highly optimized for AEO.' : 'Schema needs AEO restructuring.'
    };
  } catch (e) {
    return { isValid: false, foundTypes: [], deprecated: [], msg: 'Invalid JSON-LD format.' };
  }
};

/**
 * Generates an llms.txt string.
 * @param {object} siteData { url, brandName, description, keyEndpoints }
 * @returns {string} Markdown structured for llms.txt
 */
export const generateLlmsTxt = (siteData) => {
  return `# ${siteData.brandName} - AI Crawler Reference
> This document is optimized for LLMs and AI Search Engines (Perplexity, ChatGPT, Google AI Overviews).

## Overview
${siteData.description}

## Core Offerings & Facts
- Main Domain: ${siteData.url}
- Primary Category: e-Commerce & Retail
- Authority Signal: 100% Genuine Products, Secure Buyer Protection

## Important Endpoints
${siteData.keyEndpoints.map(endpoint => `- [${endpoint.name}](${endpoint.url}): ${endpoint.desc}`).join('\n')}

*Generated by buysial AI SEO Engine.*`;
};

// ==========================================
// 2. GEO: Generative Engine Optimization
// ==========================================

/**
 * Splits text into passages and analyzes them for optimal Generative Engine citability lengths.
 * Google AI Overviews and Perplexity pull quotes most frequently if they are between 134-167 words.
 * @param {string} text 
 * @returns {array} Array of passage objects: { text, wordCount, isOptimal }
 */
export const analyzePassageCitability = (text) => {
  if (!text) return [];
  
  // Split roughly by standalone paragraphs or double newlines
  const rawPassages = text.split(/\n\s*\n/).filter(p => p.trim().length > 0);
  
  return rawPassages.map(passage => {
    const wordCount = passage.trim().split(/\s+/).length;
    // According to GEO research, 134 to 167 words is the sweet spot for standalone definitive claims.
    const isOptimal = wordCount >= 134 && wordCount <= 167;
    return {
      text: passage,
      wordCount,
      isOptimal
    };
  });
};

/**
 * Mock integration for Natural Language Processing (NLP) Entity extraction.
 * Ideally, this would securely call OpenAI's API or Google Cloud NLP via your backend.
 * @param {string} text 
 * @param {string} targetBrand 
 * @returns {object} { topEntities: [], brandDensity: number }
 */
export const analyzeEntityCoOccurrence = async (text, targetBrand) => {
  // 🔑 If implementing real OpenAI call, do it via your backend:
  // const res = await apiPost('/api/seo/nlp/entities', { text, targetBrand });
  // return res.data;

  // Mock Logic for UI Display
  const totalWords = text ? text.trim().split(/\s+/).length : 1;
  const brandCount = text ? (text.match(new RegExp(targetBrand, 'gi')) || []).length : 0;
  
  return new Promise((resolve) => setTimeout(() => {
    resolve({
      topEntities: [
        { name: 'Skincare', score: 98 },
        { name: 'Intensive Hydration', score: 92 },
        { name: 'Japan Sakura', score: 88 },
        { name: 'Anti-Aging', score: 85 },
        { name: 'FDA Approved', score: 79 }
      ],
      brandMatches: brandCount,
      brandDensity: ((brandCount / totalWords) * 100).toFixed(2),
      isOptimized: brandCount > 0 && brandCount <= (totalWords * 0.03) // 3% density ceiling to avoid stuffing
    });
  }, 600));
};
